MiniQuotes: list[str] = [
    "not a second one...",
    "its all about perspective...",
    "now with colors!",
    "simple interfaces, complex tasks...",
    "made with <3",
    "what will you create?",
    "release date? when?",
    "is it... stable yet?",
    "the beauty is in the design!",
    "building something?",
    "on the right branch?",
    "ship it!",
    "another one bites the dust...",
    "moar particles!",
    "come join the discord! (https://discord.gg/kreGBCVsQQ)",
    "zay, wake up!",
    "its alive... its alive!!",
    "bundle of joy...",
    "a machine, turning game ideas into \'recover files\'...",
    "what have you done!?",
    "take a look inside...",
    "look at you...",
    "*commiting breaking changes*...",
    "it comes with a poster!",
    "build with structure.",
    "no! dont look!",
    "what did the dev say to the source code? \'ahhh!\'",
    "someone should see this...",
    "eat your veggies!",
    "isnt this fun?",
    "3 devs walk into the codebase...",
    "3 devs flee the codebase...",
    "now lets add multiplayer...",
    "check out r3shape on github! (https://github.com/r3shape)",
]